site_name: mappAssetInt community version
use_directory_urls: false

extra_css: [extra.css]

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
    
nav:
  - Start: index.md
  - Compatibility: compatibility/compatibility.md
  - Conversion: conversion/conversion.md
  - FAQs: faq/faq.md
  - Appendix: appendix.md
  - Test Cases: testcases.md
  - Revision: revision.md

theme:
    name: material
    logo: images/bur.png

    palette:
      scheme: default
      primary: orange
      accent: orange

    features: toc.integrate

plugins:
  - search

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
      
repo_url: https://github.com/br-automation-com/mappAssetIntEx
repo_name: GitHub Repo

